site_name: Misc Docs
extra_css: 
  - https://cdnjs.cloudflare.com/ajax/libs/vis/4.16.1/vis.min.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/vis/4.16.1/vis.min.js
  - js/colour_contrast.js
theme: readthedocs
